### ISSUE TITLE
data refresh

### ISSUE THREAD

**Issue by JoeFernando** [HughParsonage/PSMA#10]
Hugh, thanks for this package. Really useful! 

It would really help if there was a function which takes in the latest G-NAF URL address (provided by the operator) and updated the data set automatically.

If this is not too much work it would be much appreciated.

Thanks in advance.

**Comment by HughParsonage** [comment]
Please reopen if fix unsatisfactory.

**Comment by nwbort** [comment]
Looks like there's an extra line hanging around from testing in `update_data_auto` (line 26) which is now failing with the branch deleted:

https://github.com/HughParsonage/PSMA/blob/e25d96e1f8e072132c6c40b51edc525fe95052b1/R/update_data.R#L26-L27

Removed/fixed in PR.
