### ISSUE TITLE
PSMA returns a list of 10 lat/longs per address?

### ISSUE THREAD

**Issue by njtierney** [HughParsonage/PSMA#2]
Hi Hugh!

Thanks for writing this! 

I'm using some data from Brisbane - taken from here: 
https://www.data.brisbane.qld.gov.au/data/dataset/property-address-data/resource/20810036-02c5-4e70-9ed8-51ddb3529926

PSMA basically dovetails perfectly with the brisbane data, which is great. I wasn't able to get the transformation for the easting/northing, so I wanted to use PSMA to get the lat long. 

However, I get this list output, with 10 possible lat/long per answer - I was just wondering which one I should use, and what the list of 10 things means, as this isn't in the documentation?

I've got a reprex below, let me know if you have any questions :)

``` r

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(PSMA)

prop_cut <- 
tibble::tribble(
                      ~unit_number, ~house_number, ~street_name, ~street_type, ~street_suffix,               ~suburb, ~postcode,          ~address_use_type,    ~ward_name,       ~property_description,     ~northing,     ~easting,
                                NA,          "27",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.4 RP.55905 PAR BULIMBA",  "6961834.49",   "505697.5",
                                NA,          "28",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.2 RP.87085 PAR BULIMBA",   "6961816.9",  "505648.29",
                                NA,          "30",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.1 RP.87085 PAR BULIMBA",   "6961833.2",  "505644.55",
                                NA,          "33",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.6 RP.55905 PAR BULIMBA", "6961879.153", "505678.232",
                                NA,           "7",     "ABARTH",     "Street",             NA,           "CHERMSIDE",     4032L, "Uprn (Official Location)",    "MARCHANT",  "L.5 RP.118611 PAR KEDRON",  "6970343.22",  "503006.95",
                                NA,           "9",     "ABARTH",     "Street",             NA,           "CHERMSIDE",     4032L, "Uprn (Official Location)",    "MARCHANT",  "L.6 RP.118611 PAR KEDRON",  "6970339.95",   "502986.9",
                                NA,          "11",     "ABARTH",     "Street",             NA,           "CHERMSIDE",     4032L, "Uprn (Official Location)",    "MARCHANT",  "L.7 RP.118611 PAR KEDRON",  "6970318.72",  "502982.43",
                                NA,          "16",  "HILLGROVE",     "Street",             NA, "UPPER MOUNT GRAVATT",     4122L,                "Alternate",   "MACGREGOR", "L.44 RP.87380 PAR BULIMBA", "6953349.984", "508671.277",
                                NA,           "2",  "ABBEVILLE",     "Street",             NA, "UPPER MOUNT GRAVATT",     4122L, "Uprn (Official Location)",   "MACGREGOR", "L.44 RP.87380 PAR BULIMBA", "6953349.984", "508671.277",
                                NA,          "22",  "HILLGROVE",     "Street",             NA, "UPPER MOUNT GRAVATT",     4122L,                "Alternate",   "MACGREGOR", "L.42 RP.87380 PAR BULIMBA",  "6953307.34",   "508664.2"
                      )


prop <- prop_cut %>%
  mutate(psma = list(geocode(flat_number = NA_character_,
                             number_first = house_number,
                             street_name = street_name,
                             street_type = street_type,
                             postcode = postcode)))

prop$psma
#> [[1]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[2]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[3]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[4]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[5]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[6]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[7]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[8]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[9]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
#> 
#> [[10]]
#>     ordering  LATITUDE LONGITUDE
#>  1:        1 -27.46702  153.0577
#>  2:        2 -27.46718  153.0572
#>  3:        3 -27.46704  153.0571
#>  4:        4 -27.46662  153.0575
#>  5:        5 -27.39021  153.0304
#>  6:        6 -27.39024  153.0302
#>  7:        7 -27.39044  153.0301
#>  8:        8 -27.54361  153.0878
#>  9:        9 -27.54361  153.0878
#> 10:       10 -27.54399  153.0878
```

Created on 2018-06-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by HughParsonage** [comment]
Thanks for the report. The way I had been using would have been as follows:

```r
library(data.table)
prop_cut_dt <- as.data.table(prop_cut)

prop_cut_dt[, c("ii", "lat", "lon") := geocode(flat_number = NA_character_, 
                                               number_first = house_number,
                                               street_name = street_name, 
                                               street_type = street_type, 
                                               postcode = postcode)]
```

which adds three new columns `ii`, `lat`, and `lon` giving the row number, latitude and longitude.  This works nicely with data.table, but we run into problems with `mutate`. Ultimately the problem is that you need to add latitude and longitude together but separately. 

I should at least add the data.table method of mutating to `geocode`, but perhaps a new function like `mutate_geocode` should be added too.

**Comment by HughParsonage** [comment]
Hi @njtierney do you want to test out the package on the new branch? Let me know if it's no good.

```r
devtools::install_github("hughparsonage/PSMA", ref = "mutate-geocode")
```

**Comment by njtierney** [comment]
Hi @HughParsonage !

That seems to work! 

Might I suggest instead of `mutate_geocode` it is instead `add_geocode`, with the default column names to be "latitude" and "longitude", which could be modified?

Thanks again!

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(PSMA)

prop_cut <- 
  tibble::tribble(
    ~unit_number, ~house_number, ~street_name, ~street_type, ~street_suffix,               ~suburb, ~postcode,          ~address_use_type,    ~ward_name,       ~property_description,     ~northing,     ~easting,
    NA,          "27",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.4 RP.55905 PAR BULIMBA",  "6961834.49",   "505697.5",
    NA,          "28",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.2 RP.87085 PAR BULIMBA",   "6961816.9",  "505648.29",
    NA,          "30",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.1 RP.87085 PAR BULIMBA",   "6961833.2",  "505644.55",
    NA,          "33",      "AARON",     "Avenue",             NA,           "HAWTHORNE",     4171L, "Uprn (Official Location)", "MORNINGSIDE",  "L.6 RP.55905 PAR BULIMBA", "6961879.153", "505678.232",
    NA,           "7",     "ABARTH",     "Street",             NA,           "CHERMSIDE",     4032L, "Uprn (Official Location)",    "MARCHANT",  "L.5 RP.118611 PAR KEDRON",  "6970343.22",  "503006.95",
    NA,           "9",     "ABARTH",     "Street",             NA,           "CHERMSIDE",     4032L, "Uprn (Official Location)",    "MARCHANT",  "L.6 RP.118611 PAR KEDRON",  "6970339.95",   "502986.9",
    NA,          "11",     "ABARTH",     "Street",             NA,           "CHERMSIDE",     4032L, "Uprn (Official Location)",    "MARCHANT",  "L.7 RP.118611 PAR KEDRON",  "6970318.72",  "502982.43",
    NA,          "16",  "HILLGROVE",     "Street",             NA, "UPPER MOUNT GRAVATT",     4122L,                "Alternate",   "MACGREGOR", "L.44 RP.87380 PAR BULIMBA", "6953349.984", "508671.277",
    NA,           "2",  "ABBEVILLE",     "Street",             NA, "UPPER MOUNT GRAVATT",     4122L, "Uprn (Official Location)",   "MACGREGOR", "L.44 RP.87380 PAR BULIMBA", "6953349.984", "508671.277",
    NA,          "22",  "HILLGROVE",     "Street",             NA, "UPPER MOUNT GRAVATT",     4122L,                "Alternate",   "MACGREGOR", "L.42 RP.87380 PAR BULIMBA",  "6953307.34",   "508664.2"
  )


prop <- prop_cut %>%
  mutate_geocode(
    # flat_number = NA_character_,
                 number_first = house_number,
                 street_name = street_name,
                 street_type = street_type,
                 postcode = postcode,
                 new_names = c("lat", "long")
                 )

names(prop)
#>  [1] "unit_number"          "house_number"         "street_name"         
#>  [4] "street_type"          "street_suffix"        "suburb"              
#>  [7] "postcode"             "address_use_type"     "ward_name"           
#> [10] "property_description" "northing"             "easting"             
#> [13] "lat"                  "long"

knitr::kable(prop)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">unit_number</th>
<th style="text-align: left;">house_number</th>
<th style="text-align: left;">street_name</th>
<th style="text-align: left;">street_type</th>
<th style="text-align: left;">street_suffix</th>
<th style="text-align: left;">suburb</th>
<th style="text-align: right;">postcode</th>
<th style="text-align: left;">address_use_type</th>
<th style="text-align: left;">ward_name</th>
<th style="text-align: left;">property_description</th>
<th style="text-align: left;">northing</th>
<th style="text-align: left;">easting</th>
<th style="text-align: right;">lat</th>
<th style="text-align: right;">long</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">AARON</td>
<td style="text-align: left;">Avenue</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">HAWTHORNE</td>
<td style="text-align: right;">4171</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MORNINGSIDE</td>
<td style="text-align: left;">L.4 RP.55905 PAR BULIMBA</td>
<td style="text-align: left;">6961834.49</td>
<td style="text-align: left;">505697.5</td>
<td style="text-align: right;">-27.46702</td>
<td style="text-align: right;">153.0577</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">AARON</td>
<td style="text-align: left;">Avenue</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">HAWTHORNE</td>
<td style="text-align: right;">4171</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MORNINGSIDE</td>
<td style="text-align: left;">L.2 RP.87085 PAR BULIMBA</td>
<td style="text-align: left;">6961816.9</td>
<td style="text-align: left;">505648.29</td>
<td style="text-align: right;">-27.46718</td>
<td style="text-align: right;">153.0572</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">AARON</td>
<td style="text-align: left;">Avenue</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">HAWTHORNE</td>
<td style="text-align: right;">4171</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MORNINGSIDE</td>
<td style="text-align: left;">L.1 RP.87085 PAR BULIMBA</td>
<td style="text-align: left;">6961833.2</td>
<td style="text-align: left;">505644.55</td>
<td style="text-align: right;">-27.46704</td>
<td style="text-align: right;">153.0571</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">AARON</td>
<td style="text-align: left;">Avenue</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">HAWTHORNE</td>
<td style="text-align: right;">4171</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MORNINGSIDE</td>
<td style="text-align: left;">L.6 RP.55905 PAR BULIMBA</td>
<td style="text-align: left;">6961879.153</td>
<td style="text-align: left;">505678.232</td>
<td style="text-align: right;">-27.46662</td>
<td style="text-align: right;">153.0575</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">ABARTH</td>
<td style="text-align: left;">Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">CHERMSIDE</td>
<td style="text-align: right;">4032</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MARCHANT</td>
<td style="text-align: left;">L.5 RP.118611 PAR KEDRON</td>
<td style="text-align: left;">6970343.22</td>
<td style="text-align: left;">503006.95</td>
<td style="text-align: right;">-27.39021</td>
<td style="text-align: right;">153.0304</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">ABARTH</td>
<td style="text-align: left;">Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">CHERMSIDE</td>
<td style="text-align: right;">4032</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MARCHANT</td>
<td style="text-align: left;">L.6 RP.118611 PAR KEDRON</td>
<td style="text-align: left;">6970339.95</td>
<td style="text-align: left;">502986.9</td>
<td style="text-align: right;">-27.39024</td>
<td style="text-align: right;">153.0302</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">ABARTH</td>
<td style="text-align: left;">Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">CHERMSIDE</td>
<td style="text-align: right;">4032</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MARCHANT</td>
<td style="text-align: left;">L.7 RP.118611 PAR KEDRON</td>
<td style="text-align: left;">6970318.72</td>
<td style="text-align: left;">502982.43</td>
<td style="text-align: right;">-27.39044</td>
<td style="text-align: right;">153.0301</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">HILLGROVE</td>
<td style="text-align: left;">Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">UPPER MOUNT GRAVATT</td>
<td style="text-align: right;">4122</td>
<td style="text-align: left;">Alternate</td>
<td style="text-align: left;">MACGREGOR</td>
<td style="text-align: left;">L.44 RP.87380 PAR BULIMBA</td>
<td style="text-align: left;">6953349.984</td>
<td style="text-align: left;">508671.277</td>
<td style="text-align: right;">-27.54361</td>
<td style="text-align: right;">153.0878</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">ABBEVILLE</td>
<td style="text-align: left;">Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">UPPER MOUNT GRAVATT</td>
<td style="text-align: right;">4122</td>
<td style="text-align: left;">Uprn (Official Location)</td>
<td style="text-align: left;">MACGREGOR</td>
<td style="text-align: left;">L.44 RP.87380 PAR BULIMBA</td>
<td style="text-align: left;">6953349.984</td>
<td style="text-align: left;">508671.277</td>
<td style="text-align: right;">-27.54361</td>
<td style="text-align: right;">153.0878</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">HILLGROVE</td>
<td style="text-align: left;">Street</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">UPPER MOUNT GRAVATT</td>
<td style="text-align: right;">4122</td>
<td style="text-align: left;">Alternate</td>
<td style="text-align: left;">MACGREGOR</td>
<td style="text-align: left;">L.42 RP.87380 PAR BULIMBA</td>
<td style="text-align: left;">6953307.34</td>
<td style="text-align: left;">508664.2</td>
<td style="text-align: right;">-27.54399</td>
<td style="text-align: right;">153.0878</td>
</tr>
</tbody>
</table>

Created on 2018-06-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

<details>
``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.0 (2018-04-23)
#>  os       macOS High Sierra 10.13.3   
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  tz       Australia/Melbourne         
#>  date     2018-06-29                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version     date       source                             
#>  assertthat    0.2.0       2017-04-11 CRAN (R 3.5.0)                     
#>  backports     1.1.2       2017-12-13 CRAN (R 3.5.0)                     
#>  bindr         0.1.1       2018-03-13 CRAN (R 3.5.0)                     
#>  bindrcpp      0.2.2       2018-03-29 CRAN (R 3.5.0)                     
#>  callr         2.0.4       2018-05-15 CRAN (R 3.5.0)                     
#>  cli           1.0.0       2017-11-05 CRAN (R 3.5.0)                     
#>  clisymbols    1.2.0       2017-05-21 CRAN (R 3.5.0)                     
#>  crayon        1.3.4       2017-09-16 CRAN (R 3.5.0)                     
#>  data.table    1.11.4      2018-05-27 CRAN (R 3.5.0)                     
#>  debugme       1.1.0       2017-10-22 CRAN (R 3.5.0)                     
#>  desc          1.2.0       2018-05-01 CRAN (R 3.5.0)                     
#>  devtools      1.13.5.9000 2018-06-08 Github (r-lib/devtools@33a9404)    
#>  digest        0.6.15      2018-01-28 CRAN (R 3.5.0)                     
#>  dplyr       * 0.7.5       2018-05-19 CRAN (R 3.5.0)                     
#>  evaluate      0.10.1      2017-06-24 CRAN (R 3.5.0)                     
#>  fastmatch     1.1-0       2017-01-28 cran (@1.1-0)                      
#>  glue          1.2.0.9000  2018-06-27 Github (tidyverse/glue@a2c0f8b)    
#>  htmltools     0.3.6       2017-04-28 CRAN (R 3.5.0)                     
#>  hutils        1.1.0       2018-05-12 cran (@1.1.0)                      
#>  knitr         1.20        2018-02-20 CRAN (R 3.5.0)                     
#>  magrittr      1.5         2014-11-22 CRAN (R 3.5.0)                     
#>  memoise       1.1.0       2018-06-28 Github (hadley/memoise@06d16ec)    
#>  pillar        1.2.3       2018-05-25 CRAN (R 3.5.0)                     
#>  pkgbuild      1.0.0       2018-06-27 Github (r-lib/pkgbuild@0457039)    
#>  pkgconfig     2.0.1       2017-03-21 CRAN (R 3.5.0)                     
#>  pkgload       1.0.0       2018-06-27 Github (r-lib/pkgload@35efedd)     
#>  processx      3.1.0       2018-05-15 CRAN (R 3.5.0)                     
#>  PSMA        * 0.2.0       2018-06-29 Github (hughparsonage/PSMA@0d97a57)
#>  purrr         0.2.5       2018-05-29 CRAN (R 3.5.0)                     
#>  R6            2.2.2       2017-06-17 CRAN (R 3.5.0)                     
#>  Rcpp          0.12.17     2018-05-18 CRAN (R 3.5.0)                     
#>  rlang         0.2.1       2018-05-30 CRAN (R 3.5.0)                     
#>  rmarkdown     1.10        2018-06-11 CRAN (R 3.5.0)                     
#>  rprojroot     1.3-2       2018-01-03 CRAN (R 3.5.0)                     
#>  sessioninfo   1.0.0       2017-06-21 cran (@1.0.0)                      
#>  stringi       1.2.3       2018-06-12 cran (@1.2.3)                      
#>  stringr       1.3.1       2018-05-10 CRAN (R 3.5.0)                     
#>  testthat      2.0.0       2017-12-13 CRAN (R 3.5.0)                     
#>  tibble        1.4.2       2018-01-22 CRAN (R 3.5.0)                     
#>  tidyselect    0.2.4       2018-02-26 CRAN (R 3.5.0)                     
#>  usethis       1.3.0       2018-02-24 CRAN (R 3.5.0)                     
#>  withr         2.1.2       2018-03-15 CRAN (R 3.5.0)                     
#>  yaml          2.1.19      2018-05-01 CRAN (R 3.5.0)
```

</details>

**Comment by njtierney** [comment]
What do you think about `add_geocode` ?

**Comment by HughParsonage** [comment]
Thanks. Yes, added `add_geocode`. Also experimented with a different API to the geocoding data than lazy loading. Hope it works ok.
