### ISSUE TITLE
Query - other PSMA datasets

### ISSUE THREAD

**Issue by richardbeare** [HughParsonage/PSMA#9]
Hi Hugh,
Just wondering whether you have any insight as to the availability of other PSMA datasets, such as streets. It seems that the AURIN map project, which offers a ready to use workbench, has integrated many of these datasets. Web workbenches have their uses, but other interfaces, like R are useful too. See [aurin docs](https://docs.aurin.org.au/portal-help/analysing-your-data/walkability-tools/walkability001-points-to-regions/)

**Comment by HughParsonage** [comment]
Hi Richard,

Thanks for letting me know about that! I was not aware that PSMA also provides street coordinates though I would definitely want to include them if I knew where to find the data. Sadly, from a cursory search, it seems that they are only available from third-parties.  If you can point me to an open source I'd be very grateful -- though I'm guessing you wouldn't need this package as much if you had.

**Comment by richardbeare** [comment]
I've had trouble tracking down the address database that you've packaged up, so thought perhaps there's some secret source...

openstreetmap is very useful, and osmdata can fetch from it, but an official source like PSMA would be nice..

**Comment by HughParsonage** [comment]
Apologies -- I thought I had! I'll try to form a release soon.

**Comment by richardbeare** [comment]
Sorry - I am not being clear. Installing your PSMA package is fine. I was wondering where the raw data came from, hoping that there may be other interesting things there.

**Comment by HughParsonage** [comment]
https://data.gov.au/dataset/ds-dga-19432f89-dc3a-4ef3-b943-5326ef1dbecc/details?q=

**Comment by richardbeare** [comment]
:+1:
